Update snapshots and workflows for Node 20
zowe/imperative pull request #1021
Opened 2023-10-17 20:16 UTC by awharn

**What It Does**
Changes workflow to use Node 18 and 20
Updates broken snapshots

**How to Test**

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2023-10-17 21:45 UTC, gejohnston requested changes
Sorry, I think that we miscommunicated about where these changes can be made. I was thinking that we can merge from CLI/master into CLI/add-imp-v2. You were thinking that your changes have to placed into imperative/master because these files do not exist in the master branch of CLI. They only exist in the master branch of imperative.

We can no longer merge from imperative/master into cli/add-imp-v2 because there has been too much structural change.

I think that we have to ask you to discard this PR and create your changes in a local copy of cli/add-imp-v2 that you can then push to the remote version of cli/add-imp-v2.

2023-10-17 21:45 UTC, gejohnston commented on packages/imperative/src/config/cmd/report-env/EnvItems.ts
> +        probExpr: "semver.satisfies('{val}', '<17.x || 19.x || >=21.x')",
you will find that this change has already been made in cli/add-imp-v2.

2023-10-17 22:07 UTC, gejohnston commented
It occurs to me that you still have to make these changes to imperative/master just to get the current Zowe release out the door. I approve all of the updates. I just have to ask you to make them again for the CLI/add-imp-v2 branch. Sorry that you have to do duplicated work.

2023-10-24 19:38 UTC, zFernand0 commented
@awharn 
is this good to be closed?

2023-10-24 19:47 UTC, closed without merging