updated workflows
zowe/imperative pull request #985
Opened 2023-05-05 15:02 UTC by ATorrise

Action | Description
-- | -- | 
#6 | update all workflows to remove deprecation warnings
#7 | remove Node 14 from workflow matrix

2023-05-08 12:19 UTC, t1m0thyj requested changes
There are still some warnings to resolve for the Imperative CI workflow: https://github.com/zowe/imperative/actions/runs/4895746593
* `codecov/codecov-action`: v2 -> v3
* `t1m0thyj/unlock-keyring`: master -> v1

2023-05-08 14:11 UTC, zFernand0 requested changes
The changes LGTM.
I left one small comment though 😋

2023-05-08 14:11 UTC, zFernand0 commented on .github/workflows/audit.yml
|If it's ok, can we add the `zowe-v?-lts` branch to the following workflows:
- audit
- changelog
- linter (just needs to change the `v1` with `v?` 😋 

Here is an example
```yaml
on:
  pull_request:
    branches:
      - master
      - zowe-v?-lts
```

2023-05-09 03:57 UTC, t1m0thyj approved these changes

2023-05-09 12:29 UTC, zFernand0 requested changes

2023-05-09 12:29 UTC, zFernand0 commented on .github/workflows/changelog.yml
I believe I missed this one
Can we update the `awharn/check_changelog_action@v0.0.2` to `v1`?

2023-05-10 12:53 UTC, zFernand0 approved these changes

2023-05-10 12:53 UTC, merged