Update workflows
zowe/imperative pull request #988
Opened 2023-05-19 20:09 UTC by ATorrise

**What It Does**
Bug fix in auto commenter workflow 

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [x] added/updated automated tests
- updated the changelog - N/A
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2023-05-19 21:18 UTC, t1m0thyj requested changes

2023-05-19 21:18 UTC, t1m0thyj commented on .github/workflows/auto-comment.yml
>          uses: hramos/respond-to-issue-based-on-label@v2
There needs to be a hyphen before `uses` on line 14 - see https://github.com/zowe/zowe-client-python-sdk/pull/164/files for an example

2023-05-22 13:42 UTC, t1m0thyj approved these changes

2023-05-22 14:13 UTC, zFernand0 approved these changes

2023-05-22 14:15 UTC, zFernand0 commented
merging since these shouldn't require any builds to finish

2023-05-22 14:15 UTC, merged